# Generated by Django 6.0.1 on 2026-02-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(help_text='Logo da empresa (transparente de preferência)', upload_to='logos_clientes/')),
                ('categoria', models.CharField(choices=[('banco', 'Banco'), ('industria', 'Indústria'), ('comercio', 'Comércio'), ('tecnologia', 'Tecnologia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('governo', 'Governo'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição breve da empresa')),
                ('site', models.URLField(blank=True, default='', help_text='Site da empresa')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição dentro da categoria')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['categoria', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.TextField(blank=True, default='')),
                ('objetivos', models.TextField(blank=True, default='')),
                ('publico_alvo', models.TextField(blank=True, default='')),
                ('prerequisitos', models.TextField(blank=True, default='')),
                ('conteudo_programatico', models.TextField(blank=True, default='')),
                ('app', models.CharField(choices=[('Access', 'Access'), ('BI Excel', 'BI Excel'), ('Excel', 'Excel'), ('Expert', 'Expert'), ('LibreOffice', 'LibreOffice'), ('Power BI', 'Power BI'), ('PowerPoint', 'PowerPoint'), ('Project', 'Project'), ('Sharepoint', 'Sharepoint'), ('SQL', 'SQL'), ('Visio', 'Visio'), ('Workflow', 'Workflow'), ('Word', 'Word')], default='Excel', max_length=20)),
                ('versao', models.CharField(choices=[('2013', '2013'), ('2016', '2016'), ('2019', '2019'), ('365', '365'), ('2012', '2012'), ('2008', '2008'), ('LibreOffice', 'LibreOffice'), ('Workflow', 'Workflow')], default='365', max_length=20)),
                ('nivel', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Essencial', 'Essencial'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Essencial', max_length=20)),
                ('carga_horaria', models.CharField(default='8h', max_length=20)),
                ('cor', models.CharField(choices=[('#1A5E34', 'Verde escuro (Excel/BI Excel)'), ('#0F6A36', 'Verde escuro (Project/LibreOffice)'), ('#A4373A', 'Vermelho escuro (Access)'), ('#B32D28', 'Vermelho escuro (PowerPoint)'), ('#B38F00', 'Dourado escuro (Power BI)'), ('#2E3E70', 'Azul escuro (Visio/Workflow)'), ('#4B3F72', 'Roxo escuro (Expert)'), ('#2B3A67', 'Azul petróleo (SQL)'), ('#555555', 'Cinza escuro (Genérico)')], default='#1A5E34', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['app', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='bi-signpost-2', help_text='Classe do ícone Bootstrap Icons', max_length=50)),
                ('cor', models.CharField(default='#1A5E34', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoApostila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do documento', max_length=255)),
                ('arquivo', models.FileField(help_text='Arquivo PDF, DOCX, TXT, etc', upload_to='apostilas/')),
                ('embedding_model', models.CharField(choices=[('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', 'Multilingual MiniLM (Local)'), ('sentence-transformers/paraphrase-mpnet-base-v2', 'Multilingual MPNET (Local)'), ('text-embedding-3-small', 'OpenAI Embedding Small (API)'), ('text-embedding-3-large', 'OpenAI Embedding Large (API)')], default='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', help_text='Modelo usado para gerar embeddings', max_length=100)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('completo', 'Completo'), ('erro', 'Erro')], default='processando', max_length=20)),
                ('erro_mensagem', models.TextField(blank=True, default='', help_text='Mensagem de erro se status=erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostilas', to='core.curso')),
            ],
            options={
                'verbose_name': 'Documento Apostila',
                'verbose_name_plural': 'Documentos Apostilas',
                'ordering': ['-criado_em'],
                'unique_together': {('curso', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consecutivo', 'Dias Consecutivos (Seg-Qui)'), ('sabados', 'Sábados (4 sábados)')], default='consecutivo', help_text='Consecutivo: 4 dias seguidos (Seg-Qui). Sábados: 4 sábados.', max_length=20, verbose_name='Tipo de Curso')),
                ('data_inicio', models.DateField(help_text='Para sábados: primeiro sábado do curso', verbose_name='Data de Início')),
                ('data_fim', models.DateField(help_text='Para sábados: calculado automaticamente (4º sábado)', verbose_name='Data de Fim')),
                ('turno', models.CharField(choices=[('matutino', 'Matutino (08:00 - 12:00)'), ('vespertino', 'Vespertino (13:30 - 17:30)'), ('noturno', 'Noturno (18:00 - 22:00)'), ('integral', 'Integral (08:00 - 17:30)')], max_length=20, verbose_name='Turno')),
                ('vagas_totais', models.IntegerField(default=8, verbose_name='Vagas Totais')),
                ('vagas_preenchidas', models.IntegerField(default=0, verbose_name='Vagas Preenchidas')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='aberto', max_length=20, verbose_name='Status')),
                ('instrutor', models.CharField(blank=True, max_length=100, verbose_name='Instrutor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.curso')),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.modalidade')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidades',
            field=models.ManyToManyField(related_name='cursos', to='core.modalidade'),
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('conteudo', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.curso')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='CursoEmbeddingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto consolidado do curso e módulos')),
                ('embedding', models.JSONField(help_text='Vetor de embedding (lista de floats)')),
                ('embedding_model', models.CharField(default='text-embedding-3-large', max_length=100)),
                ('fonte', models.CharField(default='courses_export.json', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='core.curso')),
            ],
            options={
                'verbose_name': 'Chunk de Curso',
                'verbose_name_plural': 'Chunks de Curso',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['curso', 'embedding_model'], name='core_cursoe_curso_i_32d41a_idx')],
                'unique_together': {('curso', 'embedding_model')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chunk', models.PositiveIntegerField(help_text='Ordem do chunk no documento')),
                ('texto', models.TextField(help_text='Texto do chunk')),
                ('embedding', models.JSONField(help_text='Vetor de embedding (lista de floats)')),
                ('pagina', models.PositiveIntegerField(blank=True, help_text='Número da página (se aplicável)', null=True)),
                ('indice_inicio', models.PositiveIntegerField(help_text='Índice de início no documento original')),
                ('indice_fim', models.PositiveIntegerField(help_text='Índice de fim no documento original')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.documentoapostila')),
            ],
            options={
                'verbose_name': 'Chunk de Documento',
                'verbose_name_plural': 'Chunks de Documento',
                'ordering': ['documento', 'numero_chunk'],
                'indexes': [models.Index(fields=['documento', 'numero_chunk'], name='core_docume_documen_c39bfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrilhaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('obrigatorio', models.BooleanField(default=True, help_text='Curso obrigatório ou opcional na trilha')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.trilha')),
            ],
            options={
                'verbose_name': 'Curso da Trilha',
                'verbose_name_plural': 'Cursos da Trilha',
                'ordering': ['ordem'],
                'unique_together': {('trilha', 'curso')},
            },
        ),
    ]
