# Generated by Django 6.0.2 on 2026-02-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentoapostila',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentoapostila',
            name='curso',
        ),
        migrations.RemoveIndex(
            model_name='documentochunk',
            name='core_docume_documen_c39bfc_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(help_text='Logo da empresa', upload_to='logos_clientes/'),
        ),
        migrations.RemoveField(
            model_name='documentochunk',
            name='documento',
        ),
        migrations.DeleteModel(
            name='DocumentoApostila',
        ),
        migrations.DeleteModel(
            name='DocumentoChunk',
        ),
    ]
